/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_missile_daemon_NativeDaemonAPI21 */

#ifndef _Included_com_missile_daemon_NativeDaemonAPI21
#define _Included_com_missile_daemon_NativeDaemonAPI21
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_missile_daemon_NativeDaemonAPI21
 * Method:    doDaemon
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_missile_daemon_NativeDaemonAPI21_doDaemon
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
